# Generated by Django 4.0.6 on 2022-08-09 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mac_adress', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('greenhouse', 'greenhouse'), ('room', 'room'), ('plant', 'plant')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(choices=[('temp', 'temp'), ('lvl', 'lvl'), ('airmoist', 'airmoist'), ('soilmoist', 'soilmoist')], max_length=20)),
                ('emplacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.emplacement')),
                ('plug_in_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.device')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('TEMP', 'temperature'), ('HUMA', ' air humidity'), ('HUMS', 'soil humidity'), ('LVLW', 'water level')], max_length=128)),
                ('time', models.DateTimeField()),
                ('comming_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.sensor')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='emplacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.emplacement'),
        ),
    ]
