# Generated by Django 4.0.6 on 2022-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_sensor_number_sensor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacement',
            name='type',
            field=models.CharField(choices=[('greenhouse', 'greenhouse'), ('room', 'room'), ('plant', 'plant')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('TEMP', 'temperature'), ('HUMA', 'air humidity'), ('HUMS', 'soil humidity'), ('LVLW', 'water level')], max_length=128),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('temp', 'temp'), ('airmoist', 'airmoist'), ('soilmoist', 'soilmoist'), ('lvl', 'lvl')], max_length=20),
        ),
    ]
