# Generated by Django 4.0.6 on 2022-10-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_emplacement_type_alter_feedback_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacement',
            name='type',
            field=models.CharField(choices=[('plant', 'plant'), ('greenhouse', 'greenhouse'), ('room', 'room')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('airmoist', 'airmoist'), ('temp', 'temp'), ('soilmoist', 'soilmoist'), ('lvl', 'lvl')], max_length=20),
        ),
    ]
