# Generated by Django 4.0.6 on 2022-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_emplacement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacement',
            name='type',
            field=models.CharField(choices=[('greenhouse', 'greenhouse'), ('room', 'room'), ('plant', 'plant')], max_length=100),
        ),
    ]
