# Generated by Django 4.0.6 on 2022-11-01 22:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_emplacement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PERP', 'peristaltic pump'), ('ATOM', 'water atomiser')], max_length=128)),
                ('gpio', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
            ],
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='type',
            field=models.CharField(choices=[('room', 'room'), ('plant', 'plant'), ('greenhouse', 'greenhouse')], max_length=100),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1200)])),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_exectuted', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_executed', models.BooleanField(default=False)),
                ('actuator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.actuator')),
            ],
        ),
        migrations.AddField(
            model_name='actuator',
            name='emplacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.emplacement'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='plug_in_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.device'),
        ),
    ]
