# Generated by Django 4.0.6 on 2022-11-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_actuator_alter_emplacement_type_instruction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='type',
            field=models.CharField(choices=[('ATOM', 'water atomiser'), ('PERP', 'peristaltic pump')], max_length=128),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='type',
            field=models.CharField(choices=[('greenhouse', 'greenhouse'), ('room', 'room'), ('plant', 'plant')], max_length=100),
        ),
    ]
