# Generated by Django 4.0.6 on 2022-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_actuator_name_alter_actuator_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='type',
            field=models.CharField(choices=[('PERP', 'peristaltic pump'), ('ATOM', 'water atomiser')], max_length=128),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='is_executed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='is_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='time_exectuted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
